version: "3.8"
services:
  db:
    image: postgres:15
    container_name: library_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  library:
    build:
      context: .
    container_name: library_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
    command: ["/library/docker/app.sh"]
    ports:
      - 9000:8000
